# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
default_install_hook_types:
  - commit-msg
  - post-commit
  - pre-commit

default_stages:
  - commit

repos:
  # General checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict

  # Ruff - Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        args: [--fix]

  # Markdownlint - Markdown linter
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args: [--fix]
        stages: [commit]

  # Bandit - Find common security issues
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: [-c, bandit.yaml, -r, .]

  # Mypy - Static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [.]
        pass_filenames: false

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        description: >
          Check whether the current commit message follows commiting rules. 
          Allow empty commit messages by default, because they typically 
          indicate to Git that the commit should be aborted.
      - id: commitizen-branch
        description: >
          Check all commit messages that are already on the current branch but 
          not the default branch on the origin repository. Useful for checking 
          messages after the fact (e.g., pre-push or in CI) without an expensive 
          check of the entire repository history.
        stages:
          - post-commit
          - push

ci:
  skip: [pytest]
