---
name: release

on: # yamllint disable-line rule:truthy
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  release:
    runs-on: ubuntu-latest

    # Condition to run the job only if the push event is a tag
    if: startsWith(github.ref, "refs/tags/")

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Fetch all tags from the repository
      - name: Fetch all tags
        run: git fetch --depth=1 --tags

      - name: Setup Python
        uses: actions/setup-python@v5

      # Install git-changelog tool for generating release notes
      - name: Install git-changelog
        run: pip install git-changelog

      # Generate release notes using git-changelog
      - name: Prepare release notes
        run: git-changelog --release-notes > release-notes.md

      # Create a GitHub release using softprops/action-gh-release action
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release-notes.md # Path to the generated release notes file
